services:
  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webdb
    ports:
      - "7777:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - weblab702

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "7771:80"
    depends_on:
      - db
    networks:
      - weblab702

networks:
  weblab702:
    driver: bridge

volumes:
  mysql_data:
    driver: local
